Team2LibraryProject_01/Models/Member.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team2LibraryProject_01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Loans = new HashSet<Loan>();
            this.Reservations = new HashSet<Reservation>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int CardNo { get; set; }
        public int RoleID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Loan> Loans { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}

Team2LibraryProject_01/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Team2LibraryProject_01.Models;

namespace Team2LibraryProject_01.Controllers
{
    public class MembersController : Controller
    {
        private Team2LibraryEntities db = new Team2LibraryEntities();
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public MembersController()
        {

        }
        public MembersController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }
        // GET: /Default1/
        public ActionResult MemberIndex()
        {
            var members = db.Members.Include(m => m.Role);
            return View(members.ToList());
        }

        // GET: /Default1/Details/5
        public ActionResult MemberDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // GET: /Default1/Create
        public ActionResult Create()
        {
            ViewBag.RoleID = new SelectList(db.Roles, "RoleID", "Role1");
            return View();
        }

        // POST: /Default1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="CardNo,RoleID,FName,LName,Email,Password")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Members.Add(member);
                db.SaveChanges();
                return RedirectToAction("MemberIndex");
            }

            ViewBag.RoleID = new SelectList(db.Roles, "RoleID", "Role1", member.RoleID);
            return View(member);
        }      

        // GET: /Default1/Delete/5
        public ActionResult DeleteMember(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }


        // POST: /Default1/Delete/5
        [HttpPost, ActionName("DeleteMember")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Member member = db.Members.Find(id);

            //Check if the inventory item is currently on loan
            var loan = (from l in db.Loans
                        where l.CardNo == member.CardNo
                        select l).ToList();

            if (loan.Count > 0)
            {
                TempData["Success"] = "Error: This member is currently loaning a book. Cannot delete identity.";
                return RedirectToAction("MemberIndex");
            }


            //Remove member from Library database
            db.Members.Remove(member);
            db.SaveChanges();

            //Remove member from ASP.NET account database
            var user = await UserManager.FindByEmailAsync(member.Email);
            var deleteRole = UserManager.RemoveFromRole(user.Id, "Student");
            var deleteMember = await UserManager.DeleteAsync(user);

            TempData["Success"] = "Success: The member has been deleted.";
            return RedirectToAction("MemberIndex");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

Team2LibraryProject_01/Views/Members/Create.cshtml
@model Team2LibraryProject_01.Models.Member

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Member</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.CardNo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CardNo)
                @Html.ValidationMessageFor(model => model.CardNo)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoleID, "RoleID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoleID", String.Empty)
                @Html.ValidationMessageFor(model => model.RoleID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FName)
                @Html.ValidationMessageFor(model => model.FName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LName)
                @Html.ValidationMessageFor(model => model.LName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "MemberIndex", "Members")
</div>

Team2LibraryProject_01/Views/Members/DeleteMember.cshtml
@model Team2LibraryProject_01.Models.Member

@{
    ViewBag.Title = "Delete Member";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role.Role1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role.Role1)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "MemberIndex", "Members")
        </div>
    }
</div>

Team2LibraryProject_01/Views/Members/Details.cshtml
@model Team2LibraryProject_01.Models.Member

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Member</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role.Role1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role.Role1)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CardNo }) |
    @Html.ActionLink("Back to List", "MemberIndex", "Members")
</p>

Team2LibraryProject_01/Views/Members/EditMember.cshtml
@model Team2LibraryProject_01.Models.Member

@{
    ViewBag.Title = "Edit Member";
}

<h2>Edit Member</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.CardNo)

        <div class="form-group">
            @Html.Label("Role ID", "RoleID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoleID", String.Empty)
                @Html.ValidationMessageFor(model => model.RoleID)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("First Name", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FName)
                @Html.ValidationMessageFor(model => model.FName)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Last Name", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LName)
                @Html.ValidationMessageFor(model => model.LName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "MemberIndex", "Members")
</div>

Team2LibraryProject_01/Views/Members/MemberDetails.cshtml
@model Team2LibraryProject_01.Models.Member

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Member</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            First Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FName)
        </dd>

        <dt>
            Last Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            Role
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role.Role1)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CardNo }) |
    @Html.ActionLink("Back to List", "MemberIndex", "Members")
</p>

Team2LibraryProject_01/Views/Members/MemberIndex.cshtml
@model IEnumerable<Team2LibraryProject_01.Models.Member>

    @{
        ViewBag.Title = "Member Index";
        string message = TempData["Success"] as string;
    }

    @using GridMvc.Html
    <h2>Member Index</h2>

    <body>
        <hr />
        @if (!String.IsNullOrEmpty(message))
        {
            <hr />
            <div class="message">
                <p style="color: darkorange">@message</p>
            </div>
            <hr />
        }
        <p>
            @Html.ActionLink("Return to Admin Section", "Admin", "Home")
        </p>

        @{
            var memberGrid = new WebGrid(source: Model);
        }

        <hr />

        @helper GridManageItemColumn(int id)
        {
            @Html.ActionLink("Details", "MemberDetails", new { Id = id }, null)
        }

        @Html.Grid(Model).Columns(columns =>
                         {
                             columns.Add(model => model.FName).Titled("First Name");
                             columns.Add(model => model.LName).Titled("Last Name");
                             columns.Add(model => model.Email).Titled("Email");
                             columns.Add(model => model.Password).Titled("Password");
                             columns.Add(model => model.Role.Role1).Titled("Membership Type");
                             columns.Add(o => o.CardNo).Titled("Manage Member").Encoded(false).Sanitized(false).RenderValueAs(o => GridManageItemColumn(o.CardNo).ToHtmlString());
                         }).WithPaging(50).Sortable(true)
    </body>